apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstoneproject1
  labels:
    app: capstoneproject1
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstoneproject1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstoneproject1
    spec:
      containers:
        - image: swetlana/capstoneproject
          imagePullPolicy: Always
          name: capstoneproject
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: capstoneproject1
  labels:
    app: capstoneproject1
spec:
  type: LoadBalancer
  selector:
    app: capstoneproject1
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
